apiVersion: gitlab.organization.io/v1alpha1
kind: TeamEnvironment
metadata:
  name: team-test
  namespace: default
spec:
  crossplane:
    compositionSelector:
      matchLabels:
        type: dynamic
  environmentVariables:
    - key: API_URL
      masked: false
      protected: true
      value: https://api.example.com
    - key: DEBUG
      masked: false
      protected: false
      value: "true"
    - key: LOG_LEVEL
      masked: false
      protected: false
      value: info
  projectName: project-test
  teamName: test
  visibilityLevel: private
